# Generated by Django 3.1.2 on 2020-10-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mal_anime_prod',
            name='genres',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
