# Generated by Django 3.1.2 on 2020-10-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_auto_20201010_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mal_rating_prod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
