# Generated by Django 3.1.2 on 2021-01-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_mergedratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MergedRatings',
        ),
    ]
