# Generated by Django 3.1.2 on 2021-01-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_delete_mergedratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='mal_merged_ratings_prod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_japanese', models.CharField(max_length=200)),
                ('rating', models.IntegerField(null=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.mal_anime_prod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.mal_user_prod')),
            ],
        ),
    ]
